name             'nginx_sinatra'
maintainer       'amazedkoumei'
maintainer_email 'amazed.koumei@gmail.com'
license          'All rights reserved'
description      'Installs/Configures sinatra'
version          '0.1.0'
